### ISSUE TITLE
Xearth Q problems

### ISSUE THREAD

**Issue by Uroboros1** [Esk0r/LeagueSharp#95]
Your script, dear Honda, it disables the use of Q when is manually casted. Also, the Q does not work in laneclear, please fix this, I beg you! Otherwise this is just OP, more OP than Syndra!

**Comment by BorniPL** [comment]
Doesnt harass too - just charges and doesnt let it go ;<

**Comment by xQxCPMxQx** [comment]
Update Common pls.
